```{r Pacotes3, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(ggplot2)    
library(plotly) 
library(ggpubr) 
library(gridExtra)
library(ggthemes)
library(GGally)
library(kableExtra)
library(gtsummary)
library(xtable)
library(tinytex)
library(pander)
library(PerformanceAnalytics)
library(readxl)
```



# **CONCEITOS E DEFINIÇÕES** 

A seguir são descritos os principais termos técnicos retirados das Normas de Representação Tabular (IBGE/1993), o CTB(Anexo I, 1997), a ABTN NBR nº6067/2007 e ABNT NBR nº10697/2020, que são utilizados na elaboração deste anuário:


### **Sinistro de Trânsito**

A ocorrência que, com a participação direta de um ou mais veículos, provoca danos a este, a instalação fixa, a pessoa, animal e/ou outro veículo. 


- [X] **Atropelamento**: Acidente em que o(s) pedestre(s) ou animal(is) sofre(m) o impacto de um veículo, estando pelo menos uma das partes em movimento.

- [X] **Abalroamento**: Acidente em que um veículo é colhido lateralmente por outro veículo, também em movimento.

- [X] **Capotamento**: Acidente em que o veículo gira sobre si mesmo, em qualquer sentido, chegando a ficar com as rodas para cima, imobilizando-se em qualquer posição.

- [X] **Choque com Objeto Fixo**: Acidente em que há impacto de um veículo contra qualquer objeto fixo ou móvel, mas sem movimento.

- [X] **Colisão entre Veículos**: Acidente em que um veículo em movimento sofre o impacto de outro veículo, também em movimento.

- [X] **Queda de Ônibus**: Acidente em que há impacto em razão de queda livre dentro do ônibus, ou queda de pessoas ou cargas por ela transportadas.

- [X] **Queda de Motocicleta**: Acidente em que há impacto em razão de queda livre da motocicleta, ou queda de pessoas.

- [X] **Tombamento**: Acidente em que o veículo sai de sua posição normal, imobilizando-se sobre uma de suas laterais, sua frente ou sua traseira.



### **Veículos**

- [X] **Automóvel**: Veículo destinado ao transporte de passageiros, com capacidade para até oito pessoas, mais o
condutor; 

- [X] **Caminhão**: Veículo destinado ao transporte de carga, podendo transportar dois passageiros, mais o condutor;

- [X] **Caminhonete**: Veículo destinado ao transporte de carga com peso bruto total de até três mil e quinhentos
quilogramas;

- [X] **Camioneta**: Veículo misto destinado ao transporte de passageiros e carga no mesmo compartimento;

- [X] **Ciclomotor**: Veículo de duas ou três rodas, provido de um motor de combustão interna, cuja cilindrada não exceda a cinquenta centímetros cúbicos (3,05 polegadas cúbicas) e cuja velocidade máxima de fabricação não exceda a cinquenta quilômetros por hora;

- [X] **Motocicleta**: Veículo automotor de duas rodas, dirigido por condutor em posição montada;

- [X] **Motoneta**: Veículo automotor de duas rodas, dirigido por condutor em posição sentada;



### **Pedestre**

- [X] Toda pessoa a pé que esteja utilizando-se de vias terrestres ou áreas abertas ao público, desde que não esteja em veículo a motor, trem, bonde, transporte animal ou outro veículo, ou sobre bicicleta ou sobre animal.



### **Condutor**

- [X] Toda pessoa que conduza um veículo automotor, ou de outro tipo, incluindo os ciclos, ou que guie por uma via, cabeças de gado isoladas, rebanho, bando ou manadas, ou animais de tiro, carga ou sela. 



### **Vítimas**


- [X] **Feridos Leves**: Toda pessoa que, em consequência do acidente, tenha sofrido lesões superficiais sem a necessidade de hospitalização.
- [X] **Feridos Graves**: Vítimas de acidente cujos danos corporais (lesões) obriguem a um período de hospitalização superior a 24 horas.
- [X] **Fatal**: É qualquer acidente de trânsito em que ocorra a Morte de, pelo menos uma pessoa, até 30 dias após a data do acidente.
- [X] **Não Fatal**: É qualquer acidente de trânsito em que uma ou mais pessoas sofrem lesões, não ocasionando a morte de nenhuma delas até 30 dias após o acidente.



### **Vias Urbanas**

- [X] **Rodovia**: inclui todas as rodovias federais (BR), as rodovias do Pará (PA's) e Estradas Vicinais (VC).
- [X] **Urbana**: Todas as vias do Pará, excluindo as Rodovias;
- [X] **Rural**: Trecho de rodovia comprendido em área não edificada;



### **Turnos**

O horário dos acidentes é classificados em quatro turnos a saber:

- [X] **Madrugada**: compreende todos os acidentes ocorridos a partir da hora 00:01 minutos até às 05:59;
- [X] **Manhã**: compreende todos os acidentes ocorridos a partir da hora 05:59 minutos até às 11:59;
- [X] **Tarde**: compreende todos os acidentes ocorridos a partir da hora 12:01 minutos até às 17:59;
- [X] **Noite**: compreende todos os acidentes ocorridos a partir da hora 18:01 minutos até às 23:59;


### **Taxa de Internação Hospitalar**


- [X] A taxa de internação hospitalar é o número de casos de internação pagas no Sistema Ùnico de Saúde por acidentes de trânsito, por 10 mil habitantes, na população residente do espaço geográfico, no ano considerado.

$$ TIH_{(ATT)} = \frac{Nº \ de \ Internações }{ Nº \ de \ habitantes} \times \  10 \  mil \ (habitantes)  $$

- [X] A internação da vítima de Acidente de Trânsito retrata a gravidade do evento e constitui parte considerável dos custos decorrentes desse agravo (SOARES e BARROS, 2006).



### **Taxa de Óbito por Habitantes**


- [X] A taxa de mortalidade por acidentes de trânsito é o número de óbitos por acidentes de transporte terreste, por 100 mil habitantes, na população residente do espaço geográfico, no ano considerado.


$$ Taxa \ de \ Óbito_{(hab)} = \frac{Nº \ de \ Óbitos }{ Nº \ de \ habitantes}  \times  100 \  mil \ (hab)  $$



### **Taxa de Óbito por Veículos**

- [X] A taxa de mortalidade por veículos é o número de óbitos por acidentes de transporte terreste, por 10 mil Veículos, na frora veicular registrada do espaço geográfico, no ano considerado.


$$ Taxa \ de \ Óbito_{(veiculos)} = \frac{Nº \ de \ Óbitos }{ Nº \ de \ Veículos}  \times  \ 10 \ mil \ (veículos)$$


